### ISSUE TITLE
Syntax highlighting not working for new {%- and -%} tags

### ISSUE THREAD

**Issue by blindMoe** [siteleaf/liquid-syntax-mode#2]
Any chance you could add in the syntax highlighting for the new {%- and -%} tags that Shopify has enabled?

**Comment by sawyerh** [comment]
Hm, could you clarify or point me to a link about what you're referring to?

**Comment by blindMoe** [comment]
No Problem.  If you look at the Shopify Liquid cheatsheet ( https://www.shopify.com/partners/shopify-cheat-sheet ) you will see in the 'Whitespace Control' box that they allow the use of {%- and -%} to remove any whitespace before or after the tag.

![screen shot 2016-10-07 at 3 29 33 pm](https://cloud.githubusercontent.com/assets/1441164/19207136/fa0b5b14-8ca2-11e6-9793-2894d095da45.png)

**Comment by horsejockey** [comment]
I would also love this added in if possible.  Trying to add in the new tags but messes up they syntax recognition.
