### ISSUE TITLE
Error: The mode has failed while tokenizing the input.

### ISSUE THREAD

**Issue by spencerthayer** [siteleaf/liquid-syntax-mode#5]
The new update is broken. I'm receiving the following error, `Error: The mode has failed while tokenizing the input.` everytime I open a liquid file now and syntax coloring/highlighting isn't working.

**Comment by spencerthayer** [comment]
How can I go back to the previous version of an extension? I really need this to work today. :|

**Comment by sskylar** [comment]
Hey @spencerthayer, we haven't made any changes recently. If it broke, its likely a change in Sublime itself. You might want to try downgrading Sublime or uninstalling the plugin.

Of course, you are welcome to submit a PR with fixes!

**Comment by spencerthayer** [comment]
I understand the issue. The VS Code extension author is linking here. :\ Thanks!

**Comment by sskylar** [comment]
What was the issue?

**Comment by spencerthayer** [comment]
https://github.com/GingerBear/vscode-liquid/issues/5
